export const temples = [
  {
    id: 1,
    name: "श्री गुम्मटजी ( पद्मावतीपुरी धाम )",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "Shri Gummatji.png",
    lat: 19.1136,
    lng: 72.8697,
  },
  {
    id: 2,
    name: "श्री बंगलाजी",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "Shri Bangalaji.png",
    lat: 20.8880,
    lng: 70.4012,
  },
  {
    id: 3,
    name: "अनंत श्री प्राणनाथ जी द्वार",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "shri prannath ji gate.png",
    lat: 30.7352,
    lng: 79.0669,
  },
  {
    id: 4,
    name: "श्री गुम्मटजी ( पद्मावतीपुरी धाम )",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "Shri Gummatji.png",
    lat: 19.1136,
    lng: 72.8697,
  },
  {
    id: 5,
    name: "श्री बंगलाजी",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "Shri Bangalaji.png",
    lat: 20.8880,
    lng: 70.4012,
  },
  {
    id: 6,
    name: "अनंत श्री प्राणनाथ जी द्वार",
    location: ``,
    address: `महारानी बाईजूराज मंदिर के पास,
              धाम मोहल्ला,
              पन्ना,
              मध्य प्रदेश 488001`,
    image: "shri prannath ji gate.png",
    lat: 30.7352,
    lng: 79.0669,
  },
];
