export const temples = [
  { id: 1, image: "/temples/Shri%20Gummatji.png", name: "श्री गुम्मटजी ( पद्मावतीपुरी धाम )", address: "महारानी बाईजूराज मंदिर के पास, धाम मोहल्ला, पन्ना, मध्य प्रदेश 488001", lat: 24.726646350599218, lng: 80.18065167523824 },
  { id: 2, image: "/temples/Shri%20Bangalaji.png", name: "श्री बंगलाजी", address: "महारानी बाईजूराज मंदिर के पास, धाम मोहल्ला, पन्ना, मध्य प्रदेश 488001", lat: 24.7180, lng: 80.2030 },
  { id: 3, image: "/temples/shri%20prannath%20ji%20gate.png", name: "अनंत श्री प्राणनाथ जी द्वार", address: "महारानी बाईजूराज मंदिर के पास, धाम मोहल्ला, पन्ना, मध्य प्रदेश 488001", lat: 24.7172, lng: 80.2040 },
  { id: 4, image: "/temples/Khijada_jamnagar_temp.png", name: "श्री कृष्ण प्रणामी मंदिर (खिजड़ा मंदिर)", address: "नवतनपुरी धाम, खिजड़ा मंदिर,जामनगर, गुजरात,361001", lat: 22.4707, lng: 70.0577 },
  { id: 5, image: "/temples/surat_navichal_temp.png", name: "सूरत मंदिर", address: "श्री 5 महामंगलपुरी धाम 12/2099,नवी चाल,सैयदपुर,सूरत", lat: 21.2056, lng: 72.8277 },
  { id: 6, image: "/temples/surat-mulmilava_temp.png", name: "सूरत मंदिर", address: "श्री कृष्ण प्रणामी मूल मिलावा मानव मंदिर 56, प्राणनाथ सोसाइटी,कतारगाम ,सूरत", lat: 21.2330, lng: 72.8310 },
  { id: 7, image: "/temples/gyankendra_sarsava_temp.png", name: "श्री प्राणनाथ ज्ञानपीठ, सरसावा", address: "श्री प्राणनाथ ज्ञानपीठ, 2 किमी, नकुड़ रोड, सरसावा, माजरी कलां, उत्तर प्रदेश 247232", lat: 29.9672, lng: 77.4201 },
  { id: 8, image: "/temples/gyankendra_panna_temp.png", name: "श्री प्राणनाथ ज्ञानकेन्द्र, पन्ना", address: "श्री प्राणनाथ ज्ञानकेन्द्र, पन्ना ग्राम - रानीबाग (टगरा) मध्य प्रदेश", lat: 24.7300, lng: 80.1800 },
  { id: 9, image: "/temples/gyankendra_kanyagurukul_temp.png", name: "श्री प्राणनाथ कन्या गुरुकुल - वड़ोदरा", address: "सिया बाग मेन रोड, खंडेराव मार्केट के पीछे, कछिया पटेल वाडी, केवड़ाबाग, वडोदरा, गुजरात 390001", lat: 22.3016, lng: 73.1906 },
  { id: 10, image: "/temples/Shri%20Krishna%20Pranami%20Mandir%20-%20Christiana%20TN%20United%20States..png", name: "श्री कृष्ण प्रणामी मंदिर", address: "क्रिस्टियाना टीएन, यूनाइटेड स्टेट्स", lat: 35.5175, lng: -86.5804 },
  { id: 11, image: "/temples/nepal_salakpul_panna_temp.png", name: "श्री कृष्ण प्रणामी मंदीर - सलकपुर", address: "सलकपुर नेपाल", lat: 27.5186, lng: 87.2718 },
  { id: 12, image: "/temples/jalandar_temp.png", name: "जालंदर मंदिर", address: "श्री प्राणनाथ जी मंदिर जैन कॉलोनी,दीनदयाल उपाध्याय नगर, पानी की टंकी के सामने, जालन्धर", lat: 31.3260, lng: 75.5762 },
  { id: 13, image: "/temples/fhlika_temp.png", name: "फाजिल्का मंदिर", address: "श्री प्राणनाथ जी मंदिर पुरानी सब्जी मंडी के पास, फाजिल्का", lat: 30.4042, lng: 74.0272 },
  { id: 14, image: "/temples/abohar_temp.png", name: "अबोहर मंदिर", address: "श्री प्राणनाथ जी मंदिर बी-IX पटेल नगर, अबोहर", lat: 30.1445, lng: 74.1976 },
  { id: 15, image: "/temples/ludhiyana_temp2.png", name: "लुधियाना मंदिर", address: "श्री प्राणनाथ जी मंदिर पाम एन्क्लेव, लुधियाना", lat: 30.9010, lng: 75.8573 },
  { id: 16, image: "/temples/ludhiyana_neemvala_chowk_temp.png", name: "लुधियाना मंदिर", address: "श्री कृष्ण प्रणामी मंदिर नीम वाला चौक,लुधियाना", lat: 30.9110, lng: 75.8500 },
  { id: 17, image: "/temples/gajiyabad_temp.png", name: "गाजियाबाद मंदिर", address: "श्री कृष्ण परनामी मंदिर शिव मंदिर के पीछे, सिहानी, गाजियाबाद", lat: 28.6692, lng: 77.4538 },
  { id: 18, image: "/temples/gajiyabad_temp.png", name: "गाजियाबाद मंदिर (अतिरिक्त शाखा)", address: "श्री कृष्ण प्रणामी मंदिर, गाजियाबाद", lat: 28.6695, lng: 77.4540 },
  { id: 19, image: "/temples/400_Jaipur_temp.png", name: "जयपुर मंदिर", address: "श्री कृष्ण प्रणामी मंदिर 400, श्यामा प्रसाद मुखर्जी मार्ग,गुरुनानकपुरा,राजापार्क, जयपुर", lat: 26.8906, lng: 75.8324 },
  { id: 20, image: "/temples/jaipur_b14_temp.png", name: "जयपुर मंदिर", address: "श्री प्राणनाथ जी मंदिर बी-14, गोविन्द मार्ग, राज खुराना हॉस्पिटल के पास, आदर्श नगर, जयपुर", lat: 26.8990, lng: 75.8350 },
  { id: 21, image: "/temples/jaipur_sector_4_temp.png", name: "जयपुर मंदिर", address: "श्री कृष्ण प्रणामी मंदिर सेक्टर-4, जवाहर नगर, जयपुर", lat: 26.8851, lng: 75.8398 },
  { id: 22, image: "/temples/jaipur_rajapark_temp.png", name: "जयपुर मंदिर", address: "श्री कृष्ण प्रणामी मंदिर (बेबी जी का मंदिर) गुरुनानकपूरा, राजापार्क, जयपुर", lat: 26.8910, lng: 75.8330 },
  { id: 23, image: "/temples/ahemdabad_temp.png", name: "अहमदाबाद मंदिर", address: "उपाशना हाई स्कूल के सामने, सारंगपुर दरवाजा, अहमदाबाद", lat: 23.0225, lng: 72.5910 },
  { id: 24, image: "/temples/asam_temp.png", name: "असम मंदिर", address: "श्री प्राणनाथ जी मन्दिर शुकलाई, उदालगुड़ी, असम", lat: 26.6580, lng: 92.1150 },
  { id: 25, image: "/temples/dahod_temp.png", name: "दाहोद मंदिर", address: "श्री कृष्ण प्रणामी मंदिर गोविंदनगर, पंकज सोसाइटी, दाहोद, गुजरात", lat: 22.8360, lng: 74.2560 },
  { id: 26, image: "/temples/kanpur_govind_nagar_temp.png", name: "श्री कृष्ण प्रणामी धर्म सभा - कानपुर", address: "प्रणामी मंदिर 68/1, ब्लॉक नंबर 7, गोविन्द नगर, कानपुर", lat: 26.4499, lng: 80.3130 },
  { id: 27, image: "/temples/kanpur_63_temp.png", name: "श्री प्राणनाथजी मंदिर - कानपुर", address: "ब्लॉक नंबर 13, एच-63, गोविन्द नगर रोड, कानपुर", lat: 26.4485, lng: 80.3145 },
  { id: 28, image: "/temples/saharanpur_temp.png", name: "सहारनपुर मंदिर", address: "श्री कृष्ण प्रणामी मन्दिर धोबी घाट, सहारनपुर", lat: 29.9640, lng: 77.5460 },
  { id: 29, image: "/temples/Scranton%20penssylvania%20,USA%20Mandir.png", name: "श्री प्राणनाथ जी मंदिर (USA)", address: "स्क्रैंटन पेनसिल्वेनिया, यूएसए मंदिर", lat: 41.4090, lng: -75.6624 },
  { id: 30, image: "/temples/moyad_temple.png", name: "श्री कृष्ण प्रणामी मंदिर, मोयद", address: "मोयद, तालुका: प्रांतिज, जिला: साबरकांठा, गुजरात", lat: 23.3600, lng: 73.0500 },
  { id: 31, image: "/temples/Pural_gujarat_temp.png", name: "श्री प्राणनाथ जी मंदिर पुराल", address: "गाँव: पुराल, तालुका: हिम्मतनगर, गुजरात", lat: 23.5980, lng: 72.9710 },
  { id: 32, image: "/temples/allahbad_temp.png", name: "प्रयागराज (इलाहाबाद) मंदिर", address: "19/15, नेहरू नगर, मीरापुर, प्रयागराज", lat: 25.4358, lng: 81.8463 },
  { id: 33, image: "/temples/Gurugram_panna_temp.png", name: "श्री प्राणनाथजी मंदिर गुरुग्राम", address: "परनामी भवन, आर्यन हॉस्पिटल के पास, शिवपुरी, गुरुग्राम", lat: 28.4595, lng: 77.0266 },
  { id: 34, image: "/temples/bahraich_panna_temp.png", name: "श्री कृष्ण प्रणामी मंदिर बहराइच", address: "ग्राम बेलभरिया पोस्ट विशुनापुर जिला बहराईच", lat: 27.5750, lng: 81.5950 },
  { id: 35, image: "/temples/nepal_salakpul_panna_temp.png", name: "श्री कृष्ण प्रणामी मंदीर - सलकपुर (नेपाल)", address: "सलकपुर नेपाल", lat: 27.5186, lng: 87.2718 },
  { id: 36, image: "/temples/nepal_vitamod_temp.png", name: "श्री कृष्ण प्रणामी मंदीर - विर्तामोड", address: "विर्तामोड नेपाल", lat: 26.6380, lng: 87.9850 },
  { id: 37, image: "/temples/napal_gorkha_temp.png", name: "श्री निजानन्दी प्रणामी मंदीर - गोरखा", address: "गोरखा नेपाल", lat: 28.0000, lng: 84.6300 },
  { id: 38, image: "/temples/napal_bardhgatha_temp.png", name: "श्री निजानन्दी प्रणामी मंदीर - बर्दघाट", address: "बर्दघाट नेपाल", lat: 27.5120, lng: 83.8720 },
  { id: 39, image: "/temples/sikim_temp.png", name: "श्री प्राणनाथ जी ज्ञान केंद्र - सिक्किम", address: "श्री प्राणनाथ जी ज्ञान केंद्र नामथांग दक्षिण सिक्किम", lat: 27.2000, lng: 88.3600 },
  { id: 40, image: "/temples/himatnagar_temp.png", name: "श्री प्राणनाथ जी मंदिर - हिम्मत नगर", address: "रौनक पार्क, महावीर नगर, हिम्मत नगर, गुजरात", lat: 23.6000, lng: 72.9700 },
  { id: 41, image: "/temples/mumbai_gyankendra_temp.png", name: "श्री प्राणनाथ जी ज्ञान केंद्र - मुंबई", address: "जाम्बली गली, बोरीवली वेस्ट, मुंबई", lat: 19.2307, lng: 72.8567 },
  { id: 42, image: "/temples/mumbai_k__temp.png", name: "श्री कृष्ण प्रणामी मंदिर - मुंबई", address: "कबूतरखाना, भुलेश्वर रोड, मुंबई", lat: 18.9515, lng: 72.8285 },
  { id: 43, image: "/temples/delhi_saktinagar_temp.png", name: "श्री कृष्ण प्रणामी मंदिर - शक्ति नगर, दिल्ली", address: "10A /12, शक्ति नगर, दिल्ली, 110007", lat: 28.6850, lng: 77.1950 },
  { id: 44, image: "/temples/delhi_pritampura_temp.png", name: "श्री प्राणनाथ जी मंदिर - पीतमपुरा, दिल्ली", address: "ब्लॉक SU, उत्तरी पीतमपुरा, दिल्ली, 110034", lat: 28.7041, lng: 77.1300 },
  { id: 45, image: "/temples/hakikatnagar_delhi_temp.png", name: "श्री कृष्ण प्रणामी मंदिर - हकीकत नगर, दिल्ली", address: "78, हकीकत नगर, ओट्रम लाइन्स, दिल्ली", lat: 28.6920, lng: 77.2060 },
  { id: 46, image: "/temples/mukund_dhaam_mandir_temp.png", name: "श्री स्वामी मुकुन्द धाम - लखनऊ", address: "मुन्शीगंज, मलिहाबाद, लखनऊ, उत्तर प्रदेश", lat: 26.9200, lng: 80.7100 },
];